POST http://127.0.0.1:8000/houses/api/login
Content-Type: application/json

{
"phone":"15587497585"
}
###

PATCH http://127.0.0.1:8000/houses/api/user/to_landlord
Content-Type: application/json

{
    "phone":"12345678901"
}
###
POST http://127.0.0.1:8000/houses/api/user/add_favor
Content-Type: application/json

{
    "user_id":"kViFbYXEi7MLLZxKa7jUk7",
    "house_id":"DEMO_H"
}

###
GET http://127.0.0.1:8000/houses/api/houses/available/
###
GET  http://127.0.0.1:8000/houses/api/user/get_favor/
Content-Type: application/json

{
    "user_id":"kViFbYXEi7MLLZxKa7jUk7"
}